{"uuid": "54679d88-5255-4a42-ac7c-1394535e7ee6", "children": ["46af3f8f-aad4-4e8a-8443-6b7fe8195441"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home\n\n", "trace": "  File \"C:\\Users\\RTlabs\\PycharmProjects\\studyPython2\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\RTlabs\\PycharmProjects\\studyPython2\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\RTlabs\\PycharmProjects\\studyPython2\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\RTlabs\\PycharmProjects\\studyPython2\\lesson16\\log_selenium_1\\conftest.py\", line 31, in browser\n    driver = webdriver.Chrome(executable_path=f\"{DRIVERS}/chromedriver\")\n  File \"C:\\Users\\RTlabs\\PycharmProjects\\studyPython2\\venv\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    service_log_path, service, keep_alive)\n  File \"C:\\Users\\RTlabs\\PycharmProjects\\studyPython2\\venv\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 90, in __init__\n    self.service.start()\n  File \"C:\\Users\\RTlabs\\PycharmProjects\\studyPython2\\venv\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1648132775408, "stop": 1648132775415}], "start": 1648132775408, "stop": 1648132775957}